### ISSUE TITLE
Breaks Web Services

### ISSUE THREAD

**Issue by nwp90** [newroco/moodle-gradingform_multigraders#11]
Adding this plugin seems to have broken the ability to add functions to web services.

This is because, in lib.php, the get_external_definition_details() function returns the wrong type (should be an array). I haven't yet worked out exactly what form the guts of the returned value should take, but in the meantime caveat emptor!

**Comment by lucianpricop** [comment]
Thanks nwp90 for letting us now. Can you please refer to the documentation that specifies what get_external_definition_details() should return ? It seems moodle changed this at some point. I will search as well to see what's expected.

**Comment by pmonty** [comment]
Hey guys, I am having the same issue and it looks like this fixed it for me
```
return array($definition_extradetails);
```
i'll put a PR in and you guys can confirm

**Comment by lucianpricop** [comment]
Thanks for the suggestion. Glad that fixed the web services issue. But does the plugin still work with that change?
