### ISSUE TITLE
Grading is not saved when submitting.

### ISSUE THREAD

**Issue by capnsquarepants** [newroco/moodle-gradingform_multigraders#15]
HI there, I am testing the multigrading plugin for moodle, and I don't seem to be able to save the grades. Attached is what we see, as well as the error logs.
![grading](https://github.com/newroco/moodle-gradingform_multigraders/assets/5989455/8fe32482-efad-41ad-9a94-323450f0f041)
[php_error.log](https://github.com/newroco/moodle-gradingform_multigraders/files/13910719/php_error.log)

**Comment by lucianpricop** [comment]
Can you please tell us the version of multigraders and the version of moodle you are running?

**Comment by capnsquarepants** [comment]
We've tried both Moodle versions 4.2.5, as well as 4.3.2
The multigrader version we used was version 1.6

**Comment by lucianpricop** [comment]
The errors in the log you sent don't match with the code. If you go to for example to the error that is thrown in renderer.php at line 94 (https://github.com/newroco/moodle-gradingform_multigraders/blob/82e410c29db4dc48d1d413a11e2f55be41a5f9cd/renderer.php#L94)  you don't see anything there about the function addElement being called. The call is higher up at https://github.com/newroco/moodle-gradingform_multigraders/blob/82e410c29db4dc48d1d413a11e2f55be41a5f9cd/renderer.php#L86 line 86, so this suggests you're not running the latest code of multigraders.

**Comment by capnsquarepants** [comment]
That is odd, I got version 1.6 from here: https://moodle.org/plugins/gradingform_multigraders/versions
I just downloaded a fresh copy, and line 94 is indeed what is on line 86
![image](https://github.com/newroco/moodle-gradingform_multigraders/assets/5989455/45ad1624-2814-4ba2-ae97-ec14221a0872)
It seems that the line mismatch occurs because of this extra header:
![image](https://github.com/newroco/moodle-gradingform_multigraders/assets/5989455/f740c7db-628d-4413-ac74-544a580acc11)

**Comment by capnsquarepants** [comment]
Closing this as we decided to not use moodle.

**Comment by lucianpricop** [comment]
Actually we are working to fix this particular case. Sorry for not being as nippy as you would prefer.

**Comment by lucianpricop** [comment]
Fixed with the latest code. Will prepare a new release on moodle official page
