### ISSUE TITLE
Copy notes to feedback comments

### ISSUE THREAD

**Issue by pjonker** [newroco/moodle-gradingform_multigraders#18]
I have been testing the plugin but can't seem to get "Copy notes to feedback comments" to work? It looks like it should perform an action but nothing happens? When clicking the link I see a message in my browser javascript:void(null). Don't know if that is helpful? I am probably doing something wrong?

**Comment by lucianpricop** [comment]
Can you please attach a photo of this case so we can figure out in which case this happens? You may be one of: main grader, a second grader, none of these but have the role of Admin. When you click on it, does it not add anything in the feedback comments? Not even the name of the grader you are copying from?

**Comment by pjonker** [comment]
https://github.com/newroco/moodle-gradingform_multigraders/assets/855826/500d0565-04f9-4a43-9fc4-348fe3b2a4f8

Ik could give you access to the actual site if that helps?
