### ISSUE TITLE
Span tags in subject line notification

### ISSUE THREAD

**Issue by asudduth-moodle** [newroco/moodle-gradingform_multigraders#22]
Hello,

I am using Moodle 4.2. When sending secondary grader messages the email subject line is including the html code and span tags. Do you have a suggestion on how to change the subject line message to avoid the html including the code for url linking the assignment?

**Comment by lucianpricop** [comment]
This is the same as https://github.com/newroco/moodle-gradingform_multigraders/issues/19 which was already fixed
